# GoReleaser configuration for wrkq
# https://goreleaser.com

version: 2

project_name: wrkq

before:
  hooks:
    # Ensure dependencies are up to date
    - go mod tidy
    # Run tests before building
    - go test ./...

builds:
  - id: wrkq
    main: ./cmd/wrkq
    binary: wrkq
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/lherron/wrkq/internal/cli.Version={{.Version}}
      - -X github.com/lherron/wrkq/internal/cli.GitCommit={{.Commit}}
      - -X github.com/lherron/wrkq/internal/cli.BuildDate={{.Date}}

  - id: wrkqadm
    main: ./cmd/wrkqadm
    binary: wrkqadm
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/lherron/wrkq/internal/cli.Version={{.Version}}
      - -X github.com/lherron/wrkq/internal/cli.GitCommit={{.Commit}}
      - -X github.com/lherron/wrkq/internal/cli.BuildDate={{.Date}}

archives:
  - id: default
    format: tar.gz
    builds:
      - wrkq
      - wrkqadm
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- if eq .Os "darwin" }}macOS
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - README.md
      - LICENSE*
      - docs/*

# Homebrew tap
brews:
  - name: wrkq
    repository:
      owner: lherron
      name: homebrew-wrkq
    directory: Formula
    homepage: "https://github.com/lherron/wrkq"
    description: "Task management CLI for agent/human collaboration"
    license: "MIT"
    install: |
      bin.install "wrkq"
      bin.install "wrkqadm"
    test: |
      system "#{bin}/wrkq", "--version"
      system "#{bin}/wrkqadm", "--version"
    dependencies:
      - name: sqlite
        type: recommended

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
  groups:
    - title: Features
      regexp: '^feat:'
      order: 0
    - title: Bug Fixes
      regexp: '^fix:'
      order: 1
    - title: Others
      order: 999

# SBOM generation
sboms:
  - id: default
    artifacts: archive
    documents:
      - >-
        {{ .ProjectName }}_{{ .Version }}_
        {{- if eq .Os "darwin" }}macOS
        {{- else }}{{ .Os }}{{ end }}_
        {{- if eq .Arch "amd64" }}x86_64
        {{- else if eq .Arch "386" }}i386
        {{- else }}{{ .Arch }}{{ end }}.sbom.json

# Release configuration
release:
  github:
    owner: lherron
    name: wrkq
  prerelease: auto
  mode: replace
  header: |
    ## wrkq {{ .Version }}

    **Full Changelog**: https://github.com/lherron/wrkq/compare/{{ .PreviousTag }}...{{ .Tag }}

    ### Installation

    #### Homebrew (macOS/Linux)
    ```bash
    brew tap lherron/wrkq
    brew install wrkq
    ```

    #### Manual Installation
    Download the appropriate archive for your platform below, extract it, and place the binaries in your `PATH`.
  footer: |
    ---
    **Full documentation**: https://github.com/lherron/wrkq

    Report issues at https://github.com/lherron/wrkq/issues

# Announce (optional - for future use)
announce:
  skip: true

# Signing (optional - for future use)
signs:
  - cmd: cosign
    artifacts: checksum
    signature: "${artifact}.sig"
    certificate: "${artifact}.pem"
    args:
      - sign-blob
      - --output-signature
      - "${artifact}.sig"
      - --output-certificate
      - "${artifact}.pem"
      - "${artifact}"
    env:
      - COSIGN_EXPERIMENTAL=1
