package workrpc

import (
	"sort"

	"github.com/lherron/wrkq/internal/wrkfapi"
	"github.com/lherron/wrkq/internal/wrkqapi"
)

// Protocol catalogs (T-07090). These are pure name lists feeding
// ProtocolSchemaHash, so they stay untagged: the portable client must be able
// to compute and verify the wire identity without linking the server registry.

func MethodCatalog() []string {
	methods := append([]string{}, methodCatalog...)
	sort.Strings(methods)
	return methods
}

func ErrorCodeCatalog() []string {
	codes := []string{
		CodeWRKQNotFound,
		CodeWRKQValidation,
		CodeWRKQConflict,
		CodeWRKQForbidden,
		CodeWRKQPermissionDenied,
		CodeWRKQMigrationRequired,
		wrkqapi.CodeAlreadyClaimed,
		wrkqapi.CodeWrongState,
		wrkqapi.CodeClaimSuperseded,
		wrkqapi.CodeNodeIdentity,
		wrkfapi.CodeNotFound,
		wrkfapi.CodeValidation,
		wrkfapi.CodeStaleRevision,
		wrkfapi.CodeTransitionBlocked,
		wrkfapi.CodeRoleDenied,
		wrkfapi.CodeIdempotencyMismatch,
		wrkfapi.CodeLeaseConflict,
		wrkfapi.CodeEffectNotDeliverable,
		wrkfapi.CodeHookFailed,
		wrkfapi.CodeKindRoleDenied,
		wrkfapi.CodeLinkageUnresolved,
		wrkfapi.CodeLinkageStale,
		wrkfapi.CodeSuspended,
		wrkfapi.CodeSuspensionNotFound,
		CodeWorkRPCInternal,
	}
	sort.Strings(codes)
	return codes
}

var methodCatalog = []string{
	"rpc.initialize",
	"rpc.shutdown",
	"rpc.exit",
	"$/cancelRequest",
	"wrkq.task.create",
	"wrkq.task.show",
	"wrkq.task.catView",
	"wrkq.task.list",
	"wrkq.task.lsView",
	"wrkq.task.findListView",
	"wrkq.history.listView",
	"wrkq.history.tailView",
	"wrkq.monitor.eventsView",
	"wrkq.monitor.stateView",
	"wrkq.task.treeView",
	"wrkq.task.blockedView",
	"wrkq.task.inboxView",
	"wrkq.task.copy",
	"wrkq.task.update",
	"wrkq.task.claim",
	"wrkq.task.claimValidate",
	"wrkq.task.release",
	"wrkq.task.move",
	"wrkq.task.acknowledge",
	"wrkq.task.delete",
	"wrkq.task.restore",
	"wrkq.promise.add",
	"wrkq.promise.show",
	"wrkq.promise.list",
	"wrkq.promise.ready",
	"wrkq.promise.edit",
	"wrkq.promise.renew",
	"wrkq.promise.resolve",
	"wrkq.promise.abandon",
	"wrkq.promise.attach",
	"wrkq.promise.detach",
	"wrkq.promise.delete",
	"wrkq.room.say",
	"wrkq.room.open",
	"wrkq.room.show",
	"wrkq.room.list",
	"wrkq.room.logView",
	"wrkq.room.close",
	"wrkq.room.reopen",
	"wrkq.room.hide",
	"wrkq.room.unhide",
	"wrkq.room.join",
	"wrkq.room.leave",
	"wrkq.room.membersView",
	"wrkq.envelope.show",
	"wrkq.envelope.inboxView",
	"wrkq.envelope.defer",
	"wrkq.envelope.ack",
	"wrkq.envelope.present",
	"wrkq.envelope.pendingView",
	"wrkq.envelope.roundEnded",
	"wrkq.envelope.birthEnvelope",
	"wrkq.comment.add",
	"wrkq.comment.list",
	"wrkq.comment.show",
	"wrkq.comment.catView",
	"wrkq.comment.listView",
	"wrkq.comment.delete",
	"wrkq.attachment.add",
	"wrkq.attachment.addBytes",
	"wrkq.attachment.getBytes",
	"wrkq.attachment.list",
	"wrkq.attachment.listView",
	"wrkq.attachment.show",
	"wrkq.attachment.remove",
	"wrkq.relation.add",
	"wrkq.relation.list",
	"wrkq.relation.listView",
	"wrkq.relation.remove",
	"wrkq.container.create",
	"wrkq.container.update",
	"wrkq.container.campaignConvert",
	"wrkq.container.campaignActivate",
	"wrkq.container.campaignUpdate",
	"wrkq.container.campaignClose",
	"wrkq.container.campaignPortfolio",
	"wrkq.container.timelineView",
	"wrkq.container.move",
	"wrkq.container.webhookSet",
	"wrkq.container.archive",
	"wrkq.container.restore",
	"wrkq.container.delete",
	"wrkq.container.deleteRecursive",
	"wrkq.container.show",
	"wrkq.container.catView",
	"wrkq.container.list",
	"wrkq.container.taskCounts",
	"wrkq.project.listView",
	"wrkq.project.setRoot",
	"wrkq.webhook.add",
	"wrkq.webhook.remove",
	"wrkq.webhook.listView",
	"wrkq.workflow.attach",
	"wrkq.workflow.inspect",
	"wrkq.workflow.instances",
	"wrkq.workflow.timeline",
	"wrkq.workflow.refresh",
	"wrkq.workflow.syncMeta",
	"wrkq.handoff.create",
	"wrkq.handoff.get",
	"wrkq.handoff.listView",
	"wrkq.handoff.searchView",
	"wrkq.handoff.acknowledge",
	"wrkq.search.listView",
	"wrkq.index.status",
	"wrkq.index.update",
	"wrkq.index.rebuild",
	"wrkq.index.vacuum",
	"wrkq.index.pause",
	"wrkq.index.resume",
	"wrkf.workflow.validate",
	"wrkf.workflow.show",
	"wrkf.workflow.list",
	"wrkf.workflow.diff",
	"wrkf.workflow.install",
	"wrkf.workflow.discontinue",
	"wrkf.workflow.reinstate",
	"wrkf.instance.show",
	"wrkf.instance.next",
	"wrkf.instance.cancel",
	"wrkf.evidence.add",
	"wrkf.evidence.list",
	"wrkf.evidence.show",
	"wrkf.evidence.suggest",
	"wrkf.evidence.schema",
	"wrkf.ledger.append",
	"wrkf.ledger.list",
	"wrkf.event.query",
	"wrkf.role.list",
	"wrkf.role.bind",
	"wrkf.role.unbind",
	"wrkf.role.set",
	"wrkf.obligation.list",
	"wrkf.obligation.show",
	"wrkf.obligation.satisfy",
	"wrkf.obligation.waive",
	"wrkf.obligation.cancel",
	"wrkf.obligation.create",
	"wrkf.check.preflight",
	"wrkf.check.run",
	"wrkf.check.show",
	"wrkf.check.list",
	"wrkf.hook.list",
	"wrkf.hook.show",
	"wrkf.hook.run",
	"wrkf.transition.apply",
	"wrkf.suspension.resolve",
	"wrkf.supervisor.call",
	"wrkf.supervisor.escalate",
	"wrkf.watch.snapshot",
	"wrkf.watch.events",
	"wrkf.run.start",
	"wrkf.run.bindExternal",
	"wrkf.run.finish",
	"wrkf.run.fail",
	"wrkf.run.show",
	"wrkf.run.list",
	"wrkf.action.next",
	"wrkf.action.claim",
	"wrkf.action.settle",
	"wrkf.action.start",
	"wrkf.action.bindExternal",
	"wrkf.action.complete",
	"wrkf.action.fail",
	"wrkf.action.heartbeat",
	"wrkf.action.renewLease",
	"wrkf.action.show",
	"wrkf.action.list",
	"wrkf.effect.list",
	"wrkf.effect.show",
	"wrkf.effect.claim",
	"wrkf.effect.ack",
	"wrkf.effect.fail",
	"wrkf.effect.retry",
	"wrkf.effect.deliver",
}

var dtoCatalog = []string{
	"RPCInitializeResult", // rpc.initialize compatibility handshake, including server build provenance
	"WrkqTask",
	"WrkqTaskCopyParams", // wrkq.task.copy request envelope (server-owned deep copy)
	"WrkqTaskCopyResult", // wrkq.task.copy per-source outcome (legacy copyResult output shape)
	"WrkqTaskClaim",
	"WrkqPromise",
	"WrkqPromiseSubjectRef",
	"WrkqPromiseListResult",
	"WrkqPromiseAddParams",
	"WrkqPromiseShowParams",
	"WrkqPromiseListParams",
	"WrkqPromiseReadyParams",
	"WrkqPromiseEditParams",
	"WrkqPromiseReviewParams",
	"WrkqPromiseRetargetParams",
	"WrkqPromiseDeleteParams",
	"WrkqRoom",
	"WrkqRoomWorkRef",
	"WrkqRoomLink",
	"WrkqRoomListResult",
	"WrkqRoomLogView",
	"WrkqRoomMember",
	"WrkqRoomMembersView",
	"WrkqRoomSayResult",
	"WrkqEnvelope",
	"WrkqEnvelopeParty",
	"WrkqEnvelopePresentation",
	"WrkqEnvelopeInboxGroup",
	"WrkqEnvelopeInboxView",
	"WrkqEnvelopePresentResult",
	"WrkqEnvelopePendingView",
	"WrkqRoomSayParams",
	"WrkqRoomOpenParams",
	"WrkqRoomShowParams",
	"WrkqRoomListParams",
	"WrkqRoomLogViewParams",
	"WrkqRoomLifecycleParams",
	"WrkqRoomLabelParams",
	"WrkqRoomMemberParams",
	"WrkqRoomMembersViewParams",
	"WrkqEnvelopeShowParams",
	"WrkqEnvelopeBirthEnvelopeParams",
	"WrkqEnvelopeBirth", // birth envelope read model: lowest-seq reply_required to one scope, any state (T-07655)
	"WrkqEnvelopeInboxViewParams",
	"WrkqEnvelopeDeferParams",
	"WrkqEnvelopeAckParams",
	"WrkqEnvelopePresentParams",
	"WrkqEnvelopePendingViewParams",
	"WrkqEnvelopeRoundParams",
	"WrkqTaskCatView",        // CLI compatibility projection (cat --json); nested CatView* structs are part of this DTO
	"WrkqContainerCatView",   // CLI compatibility projection (container cat)
	"WrkqCommentCatView",     // CLI compatibility projection (comment cat)
	"WrkqCommentListView",    // CLI compatibility list projection (comment ls)
	"WrkqAttachmentListView", // CLI compatibility list projection (attach ls)
	"WrkqLsListView",         // CLI compatibility list projection (ls)
	"WrkqFindListViewParams", // CLI compatibility find request (exact label filters included)
	"WrkqFindListView",       // CLI compatibility list projection (find)
	"WrkqHistoryListView",    // CLI compatibility history read model (log over event_log); nested WrkqLogEvent is part of this DTO
	"WrkqLogEvent",           // element of history.listView (the legacy logEvent row shape)
	"WrkqHistoryTailView",    // CLI compatibility bounded ASCENDING raw tail (watch / monitor --raw); nested WrkqWatchEvent is part of this DTO
	"WrkqWatchEvent",         // element of history.tailView (the legacy watchEvent row shape — INCLUDES resource_id, distinct from WrkqLogEvent)
	"WrkqMonitorEventsView",  // CLI compatibility bounded ASCENDING filtered event page (monitor watch); nested WrkqMonitorEvent is part of this DTO
	"WrkqMonitorEvent",       // element of monitor.eventsView (the legacy monitorEventLine data row)
	"WrkqMonitorStateView",   // CLI compatibility single --until condition snapshot (monitor watch/wait)
	"WrkqTreeView",           // CLI compatibility tree projection (tree); nested WrkqTreeNode is part of this DTO
	"WrkqTaskBlockedView",    // CLI compatibility projection (check blocked); nested WrkqTaskBlockedEntry is part of this DTO
	"WrkqInboxView",          // CLI compatibility list projection (check-inbox); nested WrkqInboxEntry is part of this DTO
	"CatViewRelation",        // element of relation.listView (also nested in WrkqTaskCatView)
	"WrkqTaskListResult",
	"WrkqComment",
	"WrkqCommentListResult",
	"WrkqAttachment",
	"WrkqAttachmentBytes",          // byte-transfer read chunk (attach get); byte-transfer boundary, not canonical
	"WrkqAttachmentAddBytesResult", // byte-transfer upload ack (attach put -); byte-transfer boundary, not canonical
	"WrkqRelation",
	"WrkqContainer",
	"WrkqContainerListResult",
	"WrkqContainerTaskCount",
	"WrkqContainerTaskCounts",
	"WrkqCampaignMemberDiagnostic",
	"WrkqCampaignTransitionResult",
	"WrkqCampaignProject",
	"WrkqCampaignFootprint",
	"WrkqCampaignPortfolioRow",
	"WrkqCampaignPortfolio",
	"WrkqTimelineContainer",
	"WrkqCampaignAdornment",
	"WrkqTimelineMember",
	"WrkqTimelineRollup",
	"WrkqTimelineComment",
	"WrkqTimelineOutcome",
	"WrkqTimelineTaskState",
	"WrkqTimelineContainerState",
	"WrkqTimelineEntry",
	"WrkqContainerTimelineView",
	"WrkqProjectsListView", // CLI compatibility projection (projects)
	"WrkqProjectEntry",     // element of projects listView (includes nullable registered root)
	"WebhookRow",           // element of wrkq.webhook.listView (legacy {url:<value>} row)
	"WrkqWorkflowAttachResult",
	"WrkqWorkflowInspectResult",
	"WrkqWorkflowInstancesResult",
	"WrkqWorkflowSyncMetaResult",
	"WrkqHandoff",              // handoff resource DTO (legacy handoffJSON field order)
	"WrkqHandoffCreateResult",  // wrkq.handoff.create envelope (handoff + idempotentReplay)
	"WrkqHandoffListResult",    // wrkq.handoff.listView page envelope
	"WrkqHandoffSearchResult",  // wrkq.handoff.searchView legacy search output envelope
	"WrkqSearchListViewParams", // server-owned search request (canonical exact label filters included)
	"WrkqSearchListView",       // CLI compatibility search read model (search); nested WrkqSearchResult + WrkqIndexStatus are part of this DTO
	"WrkqSearchResult",         // element of search.listView (legacy search.Result struct order)
	"WrkqIndexStatus",          // CLI compatibility index status projection (index status; legacy indexdb.Status struct order)
	"WrkfInstance",
	"WrkfEvent",
	"WrkfEventQueryResult",
	"WrkfQueriedEvent",
	"WrkfEvidence",
	"WrkfEvidenceSchema",
	"WrkfLedgerEntry",
	"WrkfLedgerListResult",
	"WrkfObligation",
	"WrkfEffect",
	"WrkfRun",
	"WrkfCheckRun",
	"WrkfTransitionResult",
	"WrkfSuspensionResolveResult", // wrkf.suspension.resolve output (cleared suspension + new state/effects)
	"WrkfInstanceCancelResult",    // wrkf.instance.cancel output (closed instance + terminalized runs)
	"WrkfWorkflowTemplateSummary",
	"WrkfWorkflowContentParams", // content-only validate request; path variants are forbidden
	"WrkfWorkflowDiffParams",    // two bounded content bodies
	"WrkfWorkflowInstallParams", // content-only install request + attribution
	"WrkfWorkflowListResult",
	"WrkfWorkflowShowResult",
	"WrkfInstallResult",
	"WrkfDiffResult",
	"WrkfSuggestResult",
	"WrkfEffectClaimResult",
	"WrkfActionClaimPredecessor", // WRKF_LEASE_CONFLICT claim-refusal data.predecessor
	"WrkfWatchSnapshot",
	"WrkfWatchEventsResult",
}
