package workrpc_test

// legacyactor_test.go — RED acceptance tests for T-04850 (gap2).
//
// Covers the three new RPC methods:
//   wrkq.admin.legacyActor.list   — return { items: WrkqLegacyActor[] }
//   wrkq.admin.legacyActor.create — persist actor, return WrkqLegacyActor DTO, log event
//   wrkq.admin.legacyActor.update — update actor via patch, log event
//
// All tests COMPILE cleanly and fail RED at runtime because:
//   - wrkq.admin.legacyActor.list, .create, .update are not yet registered →
//     server returns JSON-RPC "method not found" (-32601) instead of the DTO,
//     WRKQ_VALIDATION, or WRKQ_CONFLICT as expected.
//
// NOTE: namespace is wrkq.admin.legacyActor.* (NOT wrkq.actor.*).
// The wrkq.actor.* namespace must remain absent (method-not-found) forever.
//
// Tests are driven through the real JSON-RPC dispatch surface via p2Run / g1Run
// (go run ./cmd/wrkq rpc --stdio) — NO direct references to not-yet-existent
// Go DTO symbols or struct fields.  Seeding uses direct DB SQL (same as gap1/gap4).

import (
	"testing"

	"github.com/lherron/wrkq/internal/db"
)

// ─── gap2 seeding helpers ─────────────────────────────────────────────────────

// g2SeedActor inserts an actor row directly into dbPath (slug must be unique).
// The uuid and friendly id are auto-generated by DB triggers/defaults.
// Returns the actor's UUID.
func g2SeedActor(t *testing.T, dbPath, slug, displayName, role string) string {
	t.Helper()
	database, err := db.Open(dbPath)
	if err != nil {
		t.Fatalf("g2SeedActor: db.Open: %v", err)
	}
	defer func() { _ = database.Close() }()

	if _, err := database.Exec(
		`INSERT INTO actors (id, slug, display_name, role) VALUES ('', ?, ?, ?)`,
		slug, displayName, role,
	); err != nil {
		t.Fatalf("g2SeedActor %q: %v", slug, err)
	}
	var uuid string
	if err := database.QueryRow("SELECT uuid FROM actors WHERE slug = ?", slug).Scan(&uuid); err != nil {
		t.Fatalf("g2SeedActor: fetch uuid for %q: %v", slug, err)
	}
	return uuid
}

// g2ActorMeta reads the raw meta text from the DB for the given actor UUID.
// Returns "" when meta is NULL.
func g2ActorMeta(t *testing.T, dbPath, uuid string) string {
	t.Helper()
	database, err := db.Open(dbPath)
	if err != nil {
		t.Fatalf("g2ActorMeta: db.Open: %v", err)
	}
	defer func() { _ = database.Close() }()

	var meta *string
	if err := database.QueryRow("SELECT meta FROM actors WHERE uuid = ?", uuid).Scan(&meta); err != nil {
		t.Fatalf("g2ActorMeta %q: %v", uuid, err)
	}
	if meta == nil {
		return ""
	}
	return *meta
}

// g2CountActorEvents counts event_log rows with the given event_type and actor UUID.
// Pass "" for actorUUID to count all events of that type.
func g2CountActorEvents(t *testing.T, dbPath, eventType, actorUUID string) int {
	t.Helper()
	database, err := db.Open(dbPath)
	if err != nil {
		t.Fatalf("g2CountActorEvents: db.Open: %v", err)
	}
	defer func() { _ = database.Close() }()

	var count int
	var qErr error
	if actorUUID != "" {
		qErr = database.QueryRow(
			"SELECT COUNT(*) FROM event_log WHERE event_type = ? AND resource_uuid = ?",
			eventType, actorUUID,
		).Scan(&count)
	} else {
		qErr = database.QueryRow(
			"SELECT COUNT(*) FROM event_log WHERE event_type = ?", eventType,
		).Scan(&count)
	}
	if qErr != nil {
		t.Fatalf("g2CountActorEvents(%s): %v", eventType, qErr)
	}
	return count
}

// ─── Catalog: methods present on BOTH entrypoints ────────────────────────────

// TestLegacyActorMethods_PresentOnBothEntrypoints verifies that
// wrkq.admin.legacyActor.list, .create, and .update are registered and
// reachable on BOTH wrkq rpc --stdio AND wrkf rpc --stdio.
//
// Each method is called with empty params; an implemented method returns
// WRKQ_VALIDATION (param validation), not "method not found".
//
// RED: all three methods are unregistered → each call returns "method not found"
// → g1IsMethodNotFound returns true → test fails.
func TestLegacyActorMethods_PresentOnBothEntrypoints(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping subprocess in short mode")
	}

	methods := []string{
		"wrkq.admin.legacyActor.list",
		"wrkq.admin.legacyActor.create",
		"wrkq.admin.legacyActor.update",
	}
	entrypoints := []string{"wrkq", "wrkf"}

	for _, ep := range entrypoints {
		ep := ep
		t.Run(ep, func(t *testing.T) {
			dbPath := migratedDB(t)
			for _, method := range methods {
				method := method
				t.Run(method, func(t *testing.T) {
					// Call with empty params — registered method returns WRKQ_VALIDATION,
					// unregistered returns "method not found".
					frames := g1Run(t, ep, dbPath,
						mkRPC("m1", method, map[string]any{}),
					)
					if g1IsMethodNotFound(frames[1]) {
						t.Errorf("entrypoint %s: method %q is not registered "+
							"(got 'method not found'); must be present on both "+
							"wrkq and wrkf entrypoints", ep, method)
					}
				})
			}
		})
	}
}

// TestLegacyActorOldNamespace_IsAbsent verifies that wrkq.actor.create,
// wrkq.actor.update, and wrkq.actor.list are NOT registered on either
// entrypoint. This namespace must remain absent — use wrkq.admin.legacyActor.*
// instead.
//
// GREEN: none of these methods is registered now and none must ever be registered.
func TestLegacyActorOldNamespace_IsAbsent(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping subprocess in short mode")
	}

	forbidden := []string{
		"wrkq.actor.create",
		"wrkq.actor.update",
		"wrkq.actor.list",
	}
	entrypoints := []string{"wrkq", "wrkf"}

	for _, ep := range entrypoints {
		ep := ep
		t.Run(ep, func(t *testing.T) {
			dbPath := migratedDB(t)
			for _, method := range forbidden {
				method := method
				t.Run(method, func(t *testing.T) {
					frames := g1Run(t, ep, dbPath,
						mkRPC("m1", method, map[string]any{}),
					)
					if !g1IsMethodNotFound(frames[1]) {
						t.Errorf("entrypoint %s: forbidden method %q is registered; "+
							"the wrkq.actor.* namespace must remain absent — "+
							"use wrkq.admin.legacyActor.* instead", ep, method)
					}
				})
			}
		})
	}
}

// ─── wrkq.admin.legacyActor.create ───────────────────────────────────────────

// TestWrkqAdminLegacyActorCreate_ReturnsDTO verifies that
// wrkq.admin.legacyActor.create returns a WrkqLegacyActor DTO with all
// required camelCase fields and no DB column name or principalRef leaks.
//
// RED: method not registered → "method not found" instead of a DTO.
func TestWrkqAdminLegacyActorCreate_ReturnsDTO(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping subprocess in short mode")
	}
	dbPath := migratedDB(t)

	frames := p2Run(t, dbPath,
		mkRPC("a1", "wrkq.admin.legacyActor.create", map[string]any{
			"slug": "g2-dto-actor",
			"role": "agent",
		}),
	)
	// frames[0]=init, frames[1]=create, frames[2]=shutdown
	result := p2ResultOrFail(t, frames[1], "wrkq.admin.legacyActor.create")

	// Required camelCase fields per WrkqLegacyActor spec.
	p2AssertStr(t, result, "uuid")
	p2AssertStr(t, result, "id")
	p2AssertStr(t, result, "slug")
	p2AssertStr(t, result, "role")
	p2AssertStr(t, result, "createdAt")
	p2AssertStr(t, result, "updatedAt")

	// DB column name leaks forbidden.
	p2AssertAbsent(t, result, "display_name")
	p2AssertAbsent(t, result, "created_at")
	p2AssertAbsent(t, result, "updated_at")

	// principalRef must NOT be present — actors are legacy admin cache, not auth principals.
	p2AssertAbsent(t, result, "principalRef")
	p2AssertAbsent(t, result, "principal_ref")
}

// TestWrkqAdminLegacyActorCreate_RoleDefaultsToAgent verifies that omitting
// role defaults to "agent".
//
// RED: method not registered → "method not found".
func TestWrkqAdminLegacyActorCreate_RoleDefaultsToAgent(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping subprocess in short mode")
	}
	dbPath := migratedDB(t)

	frames := p2Run(t, dbPath,
		mkRPC("a1", "wrkq.admin.legacyActor.create", map[string]any{
			"slug": "g2-role-default",
			// role omitted — must default to "agent"
		}),
	)
	result := p2ResultOrFail(t, frames[1], "wrkq.admin.legacyActor.create role default")

	role, _ := result["role"].(string)
	if role != "agent" {
		t.Errorf("create with no role: want role=%q, got %q", "agent", role)
	}
}

// TestWrkqAdminLegacyActorCreate_InvalidRoleReturnsValidation verifies that a
// role not in {human, agent, system} returns WRKQ_VALIDATION.
//
// RED: method not registered → "method not found" (p2ErrCode returns "") instead
// of WRKQ_VALIDATION.
func TestWrkqAdminLegacyActorCreate_InvalidRoleReturnsValidation(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping subprocess in short mode")
	}
	dbPath := migratedDB(t)

	frames := p2Run(t, dbPath,
		mkRPC("a1", "wrkq.admin.legacyActor.create", map[string]any{
			"slug": "g2-bad-role",
			"role": "superuser", // not in {human|agent|system}
		}),
	)
	code := p2ErrCode(frames[1])
	if code != "WRKQ_VALIDATION" {
		t.Errorf("create with invalid role: want WRKQ_VALIDATION, got error.data.code=%q (frame=%#v)",
			code, frames[1])
	}
}

// TestWrkqAdminLegacyActorCreate_InvalidSlugReturnsValidation verifies that a
// slug that violates slug rules (e.g., uppercase or spaces) returns
// WRKQ_VALIDATION.
//
// RED: method not registered → "method not found" instead of WRKQ_VALIDATION.
func TestWrkqAdminLegacyActorCreate_InvalidSlugReturnsValidation(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping subprocess in short mode")
	}
	dbPath := migratedDB(t)

	frames := p2Run(t, dbPath,
		mkRPC("a1", "wrkq.admin.legacyActor.create", map[string]any{
			"slug": "UPPERCASE-INVALID", // must be lowercase
		}),
	)
	code := p2ErrCode(frames[1])
	if code != "WRKQ_VALIDATION" {
		t.Errorf("create with invalid slug: want WRKQ_VALIDATION, got error.data.code=%q (frame=%#v)",
			code, frames[1])
	}
}

// TestWrkqAdminLegacyActorCreate_NonObjectMetaReturnsValidation verifies that
// passing a non-object value for meta (meta must be a JSON object) returns
// WRKQ_VALIDATION.
//
// RED: method not registered → "method not found" instead of WRKQ_VALIDATION.
func TestWrkqAdminLegacyActorCreate_NonObjectMetaReturnsValidation(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping subprocess in short mode")
	}
	dbPath := migratedDB(t)

	frames := p2Run(t, dbPath,
		mkRPC("a1", "wrkq.admin.legacyActor.create", map[string]any{
			"slug": "g2-bad-meta",
			"meta": "not-a-json-object", // must be a JSON object, not a string
		}),
	)
	code := p2ErrCode(frames[1])
	if code != "WRKQ_VALIDATION" {
		t.Errorf("create with non-object meta: want WRKQ_VALIDATION, got error.data.code=%q (frame=%#v)",
			code, frames[1])
	}
}

// TestWrkqAdminLegacyActorCreate_DuplicateSlugConflict verifies that creating
// two actors with the same slug returns WRKQ_CONFLICT on the second call.
//
// RED: method not registered → "method not found" instead of WRKQ_CONFLICT.
func TestWrkqAdminLegacyActorCreate_DuplicateSlugConflict(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping subprocess in short mode")
	}
	dbPath := migratedDB(t)

	// Pre-seed an actor with the slug we will try to duplicate via RPC.
	g2SeedActor(t, dbPath, "g2-dup-slug", "Dup Actor", "agent")

	frames := p2Run(t, dbPath,
		mkRPC("a1", "wrkq.admin.legacyActor.create", map[string]any{
			"slug": "g2-dup-slug",
			"role": "agent",
		}),
	)
	code := p2ErrCode(frames[1])
	if code != "WRKQ_CONFLICT" {
		t.Errorf("create with duplicate slug: want WRKQ_CONFLICT, got error.data.code=%q (frame=%#v)",
			code, frames[1])
	}
}

// TestWrkqAdminLegacyActorCreate_EventLogged verifies that a successful create
// logs an actor.created event in event_log.
//
// RED: method not registered → no actor or event is created.
func TestWrkqAdminLegacyActorCreate_EventLogged(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping subprocess in short mode")
	}
	dbPath := migratedDB(t)

	frames := p2Run(t, dbPath,
		mkRPC("a1", "wrkq.admin.legacyActor.create", map[string]any{
			"slug": "g2-event-actor",
			"role": "agent",
		}),
	)
	result := p2ResultOrFail(t, frames[1], "wrkq.admin.legacyActor.create")

	newUUID, _ := result["uuid"].(string)
	if newUUID == "" {
		t.Fatal("create returned no uuid; cannot check event_log")
	}
	count := g2CountActorEvents(t, dbPath, "actor.created", newUUID)
	if count == 0 {
		t.Errorf("actor.created event not found in event_log for uuid=%s", newUUID)
	}
}

// ─── wrkq.admin.legacyActor.list ─────────────────────────────────────────────

// TestWrkqAdminLegacyActorList_ReturnsItems verifies that
// wrkq.admin.legacyActor.list returns { items: WrkqLegacyActor[] } with
// correctly-shaped DTO objects (camelCase fields, no DB column leaks).
//
// RED: method not registered → "method not found" instead of { items: [...] }.
func TestWrkqAdminLegacyActorList_ReturnsItems(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping subprocess in short mode")
	}
	dbPath := migratedDB(t)

	// Seed two additional actors so the list is non-trivially non-empty.
	g2SeedActor(t, dbPath, "g2-list-alice", "Alice", "human")
	g2SeedActor(t, dbPath, "g2-list-bob", "Bob", "agent")

	frames := p2Run(t, dbPath,
		mkRPC("l1", "wrkq.admin.legacyActor.list", map[string]any{}),
	)
	result := p2ResultOrFail(t, frames[1], "wrkq.admin.legacyActor.list")

	// Must have an items array.
	p2AssertHasItems(t, result, "wrkq.admin.legacyActor.list")

	items, _ := result["items"].([]any)
	// At minimum: wrkq-system (from migration) + 2 seeded actors.
	if len(items) < 2 {
		t.Errorf("list returned %d items, want ≥ 2", len(items))
	}

	// Spot-check the first item's DTO shape.
	if len(items) > 0 {
		first, _ := items[0].(map[string]any)
		if first == nil {
			t.Fatalf("items[0] is not an object: %T=%v", items[0], items[0])
		}
		// Required camelCase fields.
		for _, field := range []string{"uuid", "id", "slug", "role", "createdAt", "updatedAt"} {
			if _, ok := first[field]; !ok {
				t.Errorf("list item[0] missing required camelCase field %q", field)
			}
		}
		// No DB column leaks.
		for _, col := range []string{"display_name", "created_at", "updated_at", "principal_ref", "principalRef"} {
			if _, ok := first[col]; ok {
				t.Errorf("list item[0] must not expose DB column/field %q", col)
			}
		}
	}
}

// ─── wrkq.admin.legacyActor.update ───────────────────────────────────────────

// TestWrkqAdminLegacyActorUpdate_RejectsImmutableFields verifies that
// attempting to patch any immutable field (slug, id, uuid, createdAt) returns
// WRKQ_VALIDATION.
//
// RED: method not registered → "method not found" instead of WRKQ_VALIDATION.
func TestWrkqAdminLegacyActorUpdate_RejectsImmutableFields(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping subprocess in short mode")
	}
	dbPath := migratedDB(t)
	actorUUID := g2SeedActor(t, dbPath, "g2-immutable-actor", "Immutable Actor", "agent")

	immutableCases := []struct {
		name  string
		patch map[string]any
	}{
		{"slug", map[string]any{"slug": "new-slug"}},
		{"id", map[string]any{"id": "A-99999"}},
		{"uuid", map[string]any{"uuid": "00000000-0000-0000-0000-000000000000"}},
		{"createdAt", map[string]any{"createdAt": "2020-01-01T00:00:00Z"}},
	}

	for _, tc := range immutableCases {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			frames := p2Run(t, dbPath,
				mkRPC("u1", "wrkq.admin.legacyActor.update", map[string]any{
					"actor": actorUUID,
					"patch": tc.patch,
				}),
			)
			code := p2ErrCode(frames[1])
			if code != "WRKQ_VALIDATION" {
				t.Errorf("update with immutable field %q: want WRKQ_VALIDATION, got error.data.code=%q (frame=%#v)",
					tc.name, code, frames[1])
			}
		})
	}
}

// TestWrkqAdminLegacyActorUpdate_RejectsUnknownPatchFields verifies that
// unknown fields in the patch object return WRKQ_VALIDATION.
//
// RED: method not registered → "method not found" instead of WRKQ_VALIDATION.
func TestWrkqAdminLegacyActorUpdate_RejectsUnknownPatchFields(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping subprocess in short mode")
	}
	dbPath := migratedDB(t)
	actorUUID := g2SeedActor(t, dbPath, "g2-unknown-patch-actor", "Unknown Patch Actor", "agent")

	frames := p2Run(t, dbPath,
		mkRPC("u1", "wrkq.admin.legacyActor.update", map[string]any{
			"actor": actorUUID,
			"patch": map[string]any{
				"principalRef": "agent:some-uuid", // not a valid patch field
			},
		}),
	)
	code := p2ErrCode(frames[1])
	if code != "WRKQ_VALIDATION" {
		t.Errorf("update with unknown patch field: want WRKQ_VALIDATION, got error.data.code=%q (frame=%#v)",
			code, frames[1])
	}
}

// TestWrkqAdminLegacyActorUpdate_StaleExpectUpdatedAtConflict verifies that
// a stale expectUpdatedAt returns WRKQ_CONFLICT.
//
// RED: method not registered → "method not found" instead of WRKQ_CONFLICT.
func TestWrkqAdminLegacyActorUpdate_StaleExpectUpdatedAtConflict(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping subprocess in short mode")
	}
	dbPath := migratedDB(t)
	actorUUID := g2SeedActor(t, dbPath, "g2-stale-cas-actor", "Stale CAS Actor", "agent")

	frames := p2Run(t, dbPath,
		mkRPC("u1", "wrkq.admin.legacyActor.update", map[string]any{
			"actor":           actorUUID,
			"expectUpdatedAt": "1970-01-01T00:00:00Z", // deliberately stale
			"patch": map[string]any{
				"displayName": "Should Not Update",
			},
		}),
	)
	code := p2ErrCode(frames[1])
	if code != "WRKQ_CONFLICT" {
		t.Errorf("update with stale expectUpdatedAt: want WRKQ_CONFLICT, got error.data.code=%q (frame=%#v)",
			code, frames[1])
	}
}

// TestWrkqAdminLegacyActorUpdate_MetaNullClearsMeta verifies that
// patch:{meta:null} clears the actor's meta field in the DB.
//
// RED: method not registered → p2ResultOrFail fails immediately with "method not found".
func TestWrkqAdminLegacyActorUpdate_MetaNullClearsMeta(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping subprocess in short mode")
	}
	dbPath := migratedDB(t)

	// Seed an actor with meta already set.
	database, err := db.Open(dbPath)
	if err != nil {
		t.Fatalf("open db: %v", err)
	}
	if _, err := database.Exec(
		`INSERT INTO actors (id, slug, display_name, role, meta) VALUES ('', ?, ?, ?, ?)`,
		"g2-meta-clear", "Meta Clear Actor", "agent", `{"key":"value"}`,
	); err != nil {
		_ = database.Close()
		t.Fatalf("seed actor with meta: %v", err)
	}
	var actorUUID string
	if err := database.QueryRow("SELECT uuid FROM actors WHERE slug = 'g2-meta-clear'").Scan(&actorUUID); err != nil {
		_ = database.Close()
		t.Fatalf("fetch actor uuid: %v", err)
	}
	_ = database.Close()

	// Patch with meta:null to clear.
	frames := p2Run(t, dbPath,
		mkRPC("u1", "wrkq.admin.legacyActor.update", map[string]any{
			"actor": actorUUID,
			"patch": map[string]any{
				"meta": nil, // explicit null clears the field
			},
		}),
	)
	p2ResultOrFail(t, frames[1], "wrkq.admin.legacyActor.update meta=null")

	// After a successful update, meta must be cleared in the DB.
	metaStr := g2ActorMeta(t, dbPath, actorUUID)
	if metaStr != "" {
		t.Errorf("meta should be cleared after patch meta=null, got %q", metaStr)
	}
}

// TestWrkqAdminLegacyActorUpdate_EventLogged verifies that a successful update
// logs an actor.updated event in event_log.
//
// RED: method not registered → p2ResultOrFail fails with "method not found".
func TestWrkqAdminLegacyActorUpdate_EventLogged(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping subprocess in short mode")
	}
	dbPath := migratedDB(t)
	actorUUID := g2SeedActor(t, dbPath, "g2-update-event-actor", "Update Event Actor", "agent")

	frames := p2Run(t, dbPath,
		mkRPC("u1", "wrkq.admin.legacyActor.update", map[string]any{
			"actor": actorUUID,
			"patch": map[string]any{
				"displayName": "Updated Name",
			},
		}),
	)
	p2ResultOrFail(t, frames[1], "wrkq.admin.legacyActor.update")

	count := g2CountActorEvents(t, dbPath, "actor.updated", actorUUID)
	if count == 0 {
		t.Errorf("actor.updated event not found in event_log for uuid=%s", actorUUID)
	}
}

// TestWrkqAdminLegacyActorUpdate_UnknownActorReturnsNotFound verifies that
// update with a non-existent actor selector returns WRKQ_NOT_FOUND.
//
// RED: method not registered → "method not found" instead of WRKQ_NOT_FOUND.
func TestWrkqAdminLegacyActorUpdate_UnknownActorReturnsNotFound(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping subprocess in short mode")
	}
	dbPath := migratedDB(t)

	frames := p2Run(t, dbPath,
		mkRPC("u1", "wrkq.admin.legacyActor.update", map[string]any{
			"actor": "00000000-dead-4000-8000-000000000000", // non-existent UUID
			"patch": map[string]any{
				"displayName": "Should Not Update",
			},
		}),
	)
	code := p2ErrCode(frames[1])
	if code != "WRKQ_NOT_FOUND" {
		t.Errorf("update with non-existent actor: want WRKQ_NOT_FOUND, got error.data.code=%q (frame=%#v)",
			code, frames[1])
	}
}

// ─── Invariant: ordinary task writes succeed with no actor row ────────────────

// TestOrdinaryTaskCreate_SucceedsWithNoActorRowForPrincipal verifies that
// wrkq.task.create succeeds even when the calling principal has no corresponding
// row in the actors table.
//
// This is a GREEN regression guard: task writes must NOT require an actor row
// for the principal_ref. The legacyActor implementation must not add such a
// prerequisite.
func TestOrdinaryTaskCreate_SucceedsWithNoActorRowForPrincipal(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping subprocess in short mode")
	}
	dbPath := migratedDB(t)

	// No actor row is seeded for a hypothetical external principal.
	// The RPC server uses its DefaultActor (wrkq-system) for DB attribution;
	// principal_ref is a free-text field with no FK — task creates must succeed.
	frames := p2Run(t, dbPath,
		mkRPC("tc1", "wrkq.task.create", map[string]any{
			"title": "No Actor Row Task",
			"kind":  "task",
		}),
	)
	result := p2ResultOrFail(t, frames[1], "wrkq.task.create without actor row for principal")
	p2AssertStr(t, result, "uuid")
	p2AssertStr(t, result, "id")
}
