package archrecords

import (
	"encoding/json"
	"fmt"
	"sort"
	"strings"
)

// generatedBanner marks projection files as machine-generated. It points editors
// at the regenerate command rather than the file itself.
const generatedBanner = "<!-- GENERATED by `just architecture-records --write` from architecture/records and architecture/contracts. DO NOT EDIT BY HAND. -->"

// Projections returns the relpath→content of every generated projection derived
// from the ACTIVE records. The byte output is deterministic (records sorted by id)
// so the check-mode diff is stable.
func Projections(records []Record) (map[string]string, error) {
	active := make([]Record, 0, len(records))
	for _, r := range records {
		if r.Status == "active" {
			active = append(active, r)
		}
	}
	sort.Slice(active, func(i, j int) bool { return active[i].ID < active[j].ID })

	index, err := renderIndex(active)
	if err != nil {
		return nil, err
	}
	return map[string]string{
		"architecture/INVARIANTS.md": renderInvariants(active),
		"architecture/RISKS.md":      renderRisks(active),
		"architecture/index.jsonl":   index,
	}, nil
}

func renderInvariants(active []Record) string {
	var b strings.Builder
	b.WriteString(generatedBanner + "\n\n")
	b.WriteString("# wrkq — Active Invariants\n\n")
	b.WriteString("Projection of active `invariant` records under `architecture/records/invariants/`.\n")
	b.WriteString("The YAML records are the source of truth; regenerate with `just architecture-records --write`.\n")

	any := false
	for _, r := range active {
		if r.Kind != "invariant" {
			continue
		}
		any = true
		b.WriteString("\n## " + r.ID + "\n\n")
		b.WriteString("- **scope:** " + oneLine(r.Scope) + "\n")
		b.WriteString("- **predicate:** " + oneLine(r.Predicate) + "\n")
		if strings.TrimSpace(r.EnforcedBy) != "" {
			b.WriteString("- **enforced_by:** `" + oneLine(r.EnforcedBy) + "`\n")
		}
		b.WriteString("- **source:** " + backtickList(r.Source) + "\n")
		if len(r.RequiredTests) > 0 {
			b.WriteString("- **required_tests:** " + backtickList(r.RequiredTests) + "\n")
		}
		b.WriteString("- **last_verified:** " + recordDate(r) + "\n")
	}
	if !any {
		b.WriteString("\n_No active invariants._\n")
	}
	return b.String()
}

func renderRisks(active []Record) string {
	var b strings.Builder
	b.WriteString(generatedBanner + "\n\n")
	b.WriteString("# wrkq — Accepted Risks\n\n")
	b.WriteString("Projection of active `accepted_risk` records under `architecture/records/risks/`.\n")
	b.WriteString("The YAML records are the source of truth; regenerate with `just architecture-records --write`.\n")

	any := false
	for _, r := range active {
		if r.Kind != "accepted_risk" {
			continue
		}
		any = true
		b.WriteString("\n## " + r.ID + "\n\n")
		b.WriteString("- **severity:** " + oneLine(r.Severity) + "\n")
		b.WriteString("- **accepted_by:** " + oneLine(r.AcceptedBy) + " (" + oneLine(r.Date) + ")\n")
		b.WriteString("- **blast_radius:** " + oneLine(r.BlastRadius) + "\n")
		b.WriteString("- **mitigation:** " + oneLine(r.Mitigation) + "\n")
		if len(r.ReviewTrigger) > 0 {
			b.WriteString("- **review_trigger:** " + joinSemicolon(r.ReviewTrigger) + "\n")
		}
		b.WriteString("- **expiry:** " + expiryText(r.Expiry) + "\n")
	}
	if !any {
		b.WriteString("\n_No active accepted risks._\n")
	}
	return b.String()
}

// indexEntry is the retrieval-index row for one active record. Field order is fixed
// for deterministic JSON output (not authority — architecture/records is).
type indexEntry struct {
	ID            string   `json:"id"`
	Kind          string   `json:"kind"`
	Status        string   `json:"status"`
	OwnerProject  string   `json:"owner_project"`
	Scope         string   `json:"scope"`
	Date          string   `json:"date"`
	Source        []string `json:"source"`
	RequiredTests []string `json:"required_tests,omitempty"`
}

func renderIndex(active []Record) (string, error) {
	var b strings.Builder
	for _, r := range active {
		entry := indexEntry{
			ID:            r.ID,
			Kind:          r.Kind,
			Status:        r.Status,
			OwnerProject:  r.OwnerProject,
			Scope:         oneLine(r.Scope),
			Date:          recordDate(r),
			Source:        r.Source,
			RequiredTests: r.RequiredTests,
		}
		line, err := json.Marshal(entry)
		if err != nil {
			return "", fmt.Errorf("marshal index entry %s: %w", r.ID, err)
		}
		b.Write(line)
		b.WriteByte('\n')
	}
	return b.String(), nil
}

func oneLine(s string) string {
	return strings.Join(strings.Fields(strings.TrimSpace(s)), " ")
}

func backtickList(items []string) string {
	parts := make([]string, 0, len(items))
	for _, it := range items {
		parts = append(parts, "`"+oneLine(it)+"`")
	}
	return strings.Join(parts, ", ")
}

func joinSemicolon(items []string) string {
	parts := make([]string, 0, len(items))
	for _, it := range items {
		parts = append(parts, oneLine(it))
	}
	return strings.Join(parts, "; ")
}

func expiryText(expiry *string) string {
	if expiry == nil || strings.TrimSpace(*expiry) == "" {
		return "none"
	}
	return oneLine(*expiry)
}
